## 错误处理

flang采用 try catch finally模式处理错误。

~~~
...
try{
a = b/c
}catch{
...
}finally{
...
}

~~~

### 错误类型

所有错误类型都继承自Err类型

+ Err
  + stdErr
    + OutOfMemErr
	+ StackOverflowErr
	+ IndexOutOfRangeErr
	+ DivideByZeroErr
  + SysErr
    + IOErr
  + UserdefinedErr

用户也可以抛出错误

~~~
#[throws(Err)]
func somefunc():Int{
...
throw Err()
...
}
~~~

定义新的错误类型，只需要继承Err类型就可以了。

Err类型具有几个属性：

+ source
+ msg
+ data
+ stackTrace